name: Build
on:
  push:
    branches:
      - master
      - v*
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  single-header:
    name: Single header
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1

    - name: Make header
      run: python ./scripts/MakeSingleHeader.py CLI11.hpp

    # Build in place for simplicity - don't do this in real life!
    - name: Prepare CMake config
      run: cmake .

    - name: Make package
      run: cmake --build package_source

    - uses: actions/upload-artifact@v1
      with:
        name: CLI11.hpp
        path: CLI11.hpp

    - uses: actions/upload-artifact@v1
      with:
        name: CLI11-Source.tar.gz
        path: CLI11-*-Source.tar.gz

    - uses: actions/upload-artifact@v1
      with:
        name: CLI11-Source.zip
        path: CLI11-*-Source.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          CLI11.hpp
          CLI11-*Source.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
